### ISSUE TITLE
Create NuGet package

### ISSUE THREAD

**Issue by FantasticFiasco** [icnocop/cuite#1]
In addition to distribute CUITe using a installer, there should be an option to install CUITe using NuGet.

**Comment by icnocop** [comment]
The NuGet packages are now automatically being deployed to nuget.org by using the appveyor continuous integration server. The first version deployed was v2.0.13-beta. Thank you! :)

**Comment by FantasticFiasco** [comment]
Cool! Glad I was given the opportunity to contribute.
