### ISSUE TITLE
Unable to run cuite test locally from  Visual Studio 2013 on Win 10 machine

### ISSUE THREAD

**Issue by umakanthk** [icnocop/cuite#102]
I have a coded ui solution containing coded ui tests, whenever i try to run or debug any test from VS 2013 i get the below error in test explorer-

Unit Test Adapter threw exception: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information..

I'm using Visual studio 2013 ultimate edition, Win 10 machine. Any help in resolving the issue is highly appreciated.

**Comment by icnocop** [comment]
Retrieve the LoaderExceptions property for more information!

**Comment by umakanthk** [comment]
I am not sure how to get into details of this exception, i see this exception while i try to run a test case from MTM, Any help here is appreciated. I am able to run test case locally from the VM which is connected to Hyperv from MTM.

**Comment by icnocop** [comment]
1. In Visual Studio, Debug > Exceptions... > Check mark "Common Language Runtime Exceptions".
2. Right-click on the test and select to Debug.
3. When the exception occurs, analyze the LoaderException property in your Watch window for example.

**Comment by umakanthk** [comment]
I don't see this issue when debugging a test script locally( from visual studio 2013), i see this exception when i execute a test case from MTM(microsoft test manager), The VMs are Win 10. I am not sure what is causing this exception during MTM run. Please provide your thoughts if any.

**Comment by icnocop** [comment]
Try enabling the Assembly Binding Logs.
https://msdn.microsoft.com/en-us/library/e74a18c4(v=vs.110).aspx

**Comment by umakanthk** [comment]
Thanks for the information. When i looked at Assembly logs i noticed below -

**\* Assembly Binder Log Entry  (11/10/2016 @ 11:34:32 AM) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\QTAgent32_40.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.VisualStudio.TestTools.UITesting, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17856/DTD3TESTAUTO4.dev-sltc.com/Deployment
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = QTAgent32_40.exe

# Calling assembly : CUITe, Version=1.0.6.0, Culture=neutral, PublicKeyToken=a67a8fd362ae8334.

LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\svc_TFS_WSSService\AppData\Local\VSEQT\QTAgent\17856\DTD3TESTAUTO4.dev-sltc.com\Deployment\DTAF_VS2013.DLL.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Microsoft.VisualStudio.TestTools.UITesting, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17856/DTD3TESTAUTO4.dev-sltc.com/Deployment/Microsoft.VisualStudio.TestTools.UITesting.DLL.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17856/DTD3TESTAUTO4.dev-sltc.com/Deployment/Microsoft.VisualStudio.TestTools.UITesting/Microsoft.VisualStudio.TestTools.UITesting.DLL.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17856/DTD3TESTAUTO4.dev-sltc.com/Deployment/Microsoft.VisualStudio.TestTools.UITesting.EXE.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17856/DTD3TESTAUTO4.dev-sltc.com/Deployment/Microsoft.VisualStudio.TestTools.UITesting/Microsoft.VisualStudio.TestTools.UITesting.EXE.
LOG: All probing URLs attempted and failed.

The UITesting dll available in the machine isn't the latest one when compared the one that is being referred in my project. so i manually copied the latest one in the VM. But it didn't resolve the issue

I am not sure if this is the right way to do it or do i need to get the latest one by installing update 5 on top of VS 2013 ultimate edition? Please advice.

**Comment by icnocop** [comment]
Does the file `file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17856/DTD3TESTAUTO4.dev-sltc.com/Deployment/Microsoft.VisualStudio.TestTools.UITesting.DLL` exist?

Maybe try setting CopyLocal=true in the properties of the file reference in the project.

**Comment by umakanthk** [comment]
I did set CopyLocal=true in the properties of the file reference in the project but didn't help. Also i don't see anyfile under C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent

**Comment by icnocop** [comment]
Does `Microsoft.VisualStudio.TestTools.UITesting.DLL` exist on the test agent?

**Comment by umakanthk** [comment]
Microsoft.VisualStudio.TestTools.UITesting.DLL is found on the VM under the path 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\PublicAssemblies\

Hope i got your question correctly.

**Comment by icnocop** [comment]
Where are your test assemblies that are run by `QTAgent32_40.exe` located on the test agent?

**Comment by umakanthk** [comment]
I see that all the test assemblies are getting copied to below location during test run from MTM on test agent and those were deleted post the test execution

C:\Users\svc_TFS_WSSService\AppData\Local\VSEQT\QTAgent

**Comment by icnocop** [comment]
I'm not exactly sure why QTAgent is not automatically resolving that assembly.

In any case, maybe you can try to add the `PublicAssemblies` path to any one of the following so that the assembly can be resolved:
1. A test settings file and use it when running your tests.
https://blogs.msdn.microsoft.com/vstsqualitytools/2010/01/08/assembly-resolution-for-unit-tests/
2. The `<probing>` element of your configuration file.
https://msdn.microsoft.com/en-us/library/823z9h8w(v=vs.110).aspx
3. System PATH environment variable
4. The GAC

**Comment by umakanthk** [comment]
Thanks for your prompt responses. I tried setting up system PATH environment variable but it didn't help.
I am suspecting if there is anything to do with build definition, Attaching for reference.

Also is there any way to share my code/screen over call and troubleshoot the exception?
[BD.docx](https://github.com/icnocop/cuite/files/585465/BD.docx)

**Comment by icnocop** [comment]
It could be because you're using an older build template:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/6d6c195e-60af-49fe-8b3f-5b04dd3b85de/build-deploy-test-workflow-could-not-load-file-or-assembly?forum=vsmantest

You can also try specifying the hint path directly on the project reference:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/9effdf9f-dfdd-4d2e-9218-be4c247078f1/build-agent-cannot-reference-coded-ui-assemblies?forum=tfsbuild

**Comment by umakanthk** [comment]
I have just tried using new build template TfvcTemplate.12.xaml but it didn't help and iam still seeing same exception.

**Comment by icnocop** [comment]
Please try my other suggestions and look at the Assembly Binding Log for details about the paths QTAgent32_40.exe searches.

**Comment by icnocop** [comment]
Do Coded UI tests that don't reference CUITe work in the same environment?
Also, check that the platform configuration being built is the same one used to run the tests.

**Comment by umakanthk** [comment]
Hi,
 I have just created a new coded ui project without using CUITe but even this one failed on the environment. The platform config was set to x86(Process Architecture) and the same was choosen in build definition.

**\* Assembly Binder Log Entry  (11/14/2016 @ 7:50:40 AM) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\QTAgent32_40.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.VisualStudio.TestTools.Proxy.UITesting, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = QTAgent32_40.exe

# Calling assembly : Microsoft.VisualStudio.QualityTools.CodedUITestFramework, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.

LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\QTAgent32_40.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Microsoft.VisualStudio.TestTools.Proxy.UITesting, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/Microsoft.VisualStudio.TestTools.Proxy.UITesting.DLL.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/Microsoft.VisualStudio.TestTools.Proxy.UITesting/Microsoft.VisualStudio.TestTools.Proxy.UITesting.DLL.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/PrivateAssemblies/Microsoft.VisualStudio.TestTools.Proxy.UITesting.DLL.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/PrivateAssemblies/Microsoft.VisualStudio.TestTools.Proxy.UITesting/Microsoft.VisualStudio.TestTools.Proxy.UITesting.DLL.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/PublicAssemblies/Microsoft.VisualStudio.TestTools.Proxy.UITesting.DLL.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/PublicAssemblies/Microsoft.VisualStudio.TestTools.Proxy.UITesting/Microsoft.VisualStudio.TestTools.Proxy.UITesting.DLL.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/DataCollectors/Microsoft.VisualStudio.TestTools.Proxy.UITesting.DLL.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/DataCollectors/Microsoft.VisualStudio.TestTools.Proxy.UITesting/Microsoft.VisualStudio.TestTools.Proxy.UITesting.DLL.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/DataCollectors/x86/Microsoft.VisualStudio.TestTools.Proxy.UITesting.DLL.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/DataCollectors/x86/Microsoft.VisualStudio.TestTools.Proxy.UITesting/Microsoft.VisualStudio.TestTools.Proxy.UITesting.DLL.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/PrivateAssemblies/DataCollectors/Microsoft.VisualStudio.TestTools.Proxy.UITesting.DLL.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/PrivateAssemblies/DataCollectors/Microsoft.VisualStudio.TestTools.Proxy.UITesting/Microsoft.VisualStudio.TestTools.Proxy.UITesting.DLL.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/PrivateAssemblies/DataCollectors/x86/Microsoft.VisualStudio.TestTools.Proxy.UITesting.DLL.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/PrivateAssemblies/DataCollectors/x86/Microsoft.VisualStudio.TestTools.Proxy.UITesting/Microsoft.VisualStudio.TestTools.Proxy.UITesting.DLL.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/Microsoft.VisualStudio.TestTools.Proxy.UITesting.EXE.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/Microsoft.VisualStudio.TestTools.Proxy.UITesting/Microsoft.VisualStudio.TestTools.Proxy.UITesting.EXE.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/PrivateAssemblies/Microsoft.VisualStudio.TestTools.Proxy.UITesting.EXE.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/PrivateAssemblies/Microsoft.VisualStudio.TestTools.Proxy.UITesting/Microsoft.VisualStudio.TestTools.Proxy.UITesting.EXE.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/PublicAssemblies/Microsoft.VisualStudio.TestTools.Proxy.UITesting.EXE.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/PublicAssemblies/Microsoft.VisualStudio.TestTools.Proxy.UITesting/Microsoft.VisualStudio.TestTools.Proxy.UITesting.EXE.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/DataCollectors/Microsoft.VisualStudio.TestTools.Proxy.UITesting.EXE.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/DataCollectors/Microsoft.VisualStudio.TestTools.Proxy.UITesting/Microsoft.VisualStudio.TestTools.Proxy.UITesting.EXE.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/DataCollectors/x86/Microsoft.VisualStudio.TestTools.Proxy.UITesting.EXE.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/DataCollectors/x86/Microsoft.VisualStudio.TestTools.Proxy.UITesting/Microsoft.VisualStudio.TestTools.Proxy.UITesting.EXE.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/PrivateAssemblies/DataCollectors/Microsoft.VisualStudio.TestTools.Proxy.UITesting.EXE.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/PrivateAssemblies/DataCollectors/Microsoft.VisualStudio.TestTools.Proxy.UITesting/Microsoft.VisualStudio.TestTools.Proxy.UITesting.EXE.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/PrivateAssemblies/DataCollectors/x86/Microsoft.VisualStudio.TestTools.Proxy.UITesting.EXE.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17928/DTD3TESTAUTO3.dev-sltc.com/Deployment/PrivateAssemblies/DataCollectors/x86/Microsoft.VisualStudio.TestTools.Proxy.UITesting/Microsoft.VisualStudio.TestTools.Proxy.UITesting.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio 12.0/Common7/IDE/PublicAssemblies/Microsoft.VisualStudio.TestTools.Proxy.UITesting.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio 12.0/Common7/IDE/PublicAssemblies/Microsoft.VisualStudio.TestTools.Proxy.UITesting/Microsoft.VisualStudio.TestTools.Proxy.UITesting.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio 12.0/Common7/IDE/PublicAssemblies/Microsoft.VisualStudio.TestTools.Proxy.UITesting.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio 12.0/Common7/IDE/PublicAssemblies/Microsoft.VisualStudio.TestTools.Proxy.UITesting/Microsoft.VisualStudio.TestTools.Proxy.UITesting.EXE.
LOG: All probing URLs attempted and failed.

**Comment by umakanthk** [comment]
The VS 2013 has got update 5 available where as on the environment it has VS 2013 without any update. So iam wondering if there is a need to install update 5 so as to make it compatible at both the ends.

**Comment by umakanthk** [comment]
Update: I just installed update 5 on the environment but it didn't help!

**Comment by icnocop** [comment]
Which version of TFS is being used?

**Comment by umakanthk** [comment]
Team Foundation Server 2013- Update 5 (12.0.40629) on both client and environment

**Comment by icnocop** [comment]
You're last log indicates an error in finding Microsoft.VisualStudio.TestTools.Proxy.UITesting.dll.
Is it actually on the system where the tests are trying to run?
If so, is its version and public key token the same as what is referenced in the project?
What are the project reference properties for all the "Microsoft.VisualStudio.*" dlls?
For example, is Private/Copy Local set to true or false?
Which edition of Visual Studio 2013 is installed on the agent, Visual Studio 2013 Ultimate or Premium?

**Comment by umakanthk** [comment]
The dll is present on the system where the tests are scheduled to run and its version is 12.0.21005.1, its version and public key token are same as what is reference in the project

Not all the project reference properties for Microsoft.VisualStudio.*.dlls are set to true, except for uitesting.dll
Visual studio 2013 ultimate with update 5 is installed.

**Comment by icnocop** [comment]
Is that dll in one of the paths that QTAgent32_40.exe searched in as indicated in the log?

**Comment by umakanthk** [comment]
Yes, its there. Below is the latest log i see...

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\QTAgent32_40.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.VisualStudio.TestTools.UITesting, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
(Fully-specified)
LOG: Appbase = file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17972/DTD3TESTAUTO4.dev-sltc.com/Deployment
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = QTAgent32_40.exe

# Calling assembly : CUITe, Version=1.0.6.0, Culture=neutral, PublicKeyToken=a67a8fd362ae8334.

LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\svc_TFS_WSSService\AppData\Local\VSEQT\QTAgent\17972\DTD3TESTAUTO4.dev-sltc.com\Deployment\DTAF_VS2013.DLL.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Microsoft.VisualStudio.TestTools.UITesting, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17972/DTD3TESTAUTO4.dev-sltc.com/Deployment/Microsoft.VisualStudio.TestTools.UITesting.DLL.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17972/DTD3TESTAUTO4.dev-sltc.com/Deployment/Microsoft.VisualStudio.TestTools.UITesting/Microsoft.VisualStudio.TestTools.UITesting.DLL.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17972/DTD3TESTAUTO4.dev-sltc.com/Deployment/Microsoft.VisualStudio.TestTools.UITesting.EXE.
LOG: Attempting download of new URL file:///C:/Users/svc_TFS_WSSService/AppData/Local/VSEQT/QTAgent/17972/DTD3TESTAUTO4.dev-sltc.com/Deployment/Microsoft.VisualStudio.TestTools.UITesting/Microsoft.VisualStudio.TestTools.UITesting.EXE.
LOG: All probing URLs attempted and failed.

**Comment by icnocop** [comment]
It seems your coded ui tests don't work even without using CUITe, so there's something not set up correctly in your environment.

For example, on my machine, the file "Microsoft.VisualStudio.TestTools.Proxy.UITesting.dll" exists in "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\PrivateAssemblies", but that path is not being searched in your environment and that's probably why it's failing from the beginning.

In the log where CUITe is referenced, it's not even searching in the path where "Microsoft.VisualStudio.TestTools.UITesting.dll" exists; for example, "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\PublicAssemblies" or "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\ReferenceAssemblies\v4.0".

You might find better support in Microsoft's coded ui test forum, https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?forum=vstest, in getting help with running Coded UI test, especially when having your tests not referencing CUITe.

**Comment by umakanthk** [comment]
Thanks once again for your quick responses. 

We were referring uitesting.dll from public assemblies path and the same has been there a while ago for our other projects which worked and also these assemblies are stored in GAC we never thought of changing the reference path in our project.
on the second point, i assume that since all the necessary dlls were copied under QTAgent initially, it might be looking at this location during run.

I have also posted my query in MSDN and awaiting responses.

**Comment by icnocop** [comment]
Can you provide a link to your post on the MSDN forums please?

It may help others who also run into this issue.

Thank you.

**Comment by umakanthk** [comment]
https://social.msdn.microsoft.com/Forums/en-US/25230f86-56d5-485d-8dbc-09fcb523593b/unit-test-adapter-exception-while-executing-automated-test-case-from-microsoft-test-manager?forum=vsmantest
