### ISSUE TITLE
Does Test Agent update 5 and Test Controller update 5 works on VS  2013 

### ISSUE THREAD

**Issue by umakanthk** [icnocop/cuite#103]
I have installed Test Agent update 5 and Test Controller update 5 for VS 2013. Can i use this setup to run cuite scripts on a VM which has Win 10?

**Comment by icnocop** [comment]
I don't believe the versions of the Test Agent and Test Controller matter when running a Test Container that includes a reference to CUITe.

Please try it and let us know your results.
