### ISSUE TITLE
How to extend CUITe controls?

### ISSUE THREAD

**Issue by danielc126** [icnocop/cuite#105]
I'd like to extend the CUITe controls to support certain properties of a Custom control that are present in our application without changing the CUITe source code. For example how to create a new class that would extend the CUITe.Controls.SilverlightControls.SilverlightComboBox to either override some of the methods or add new methods to handle certain functionalities of a custom control while providing the access to the existing methods and properties for the base class in CUITe. I'd greatly appreciate a small working sample. I did try to create a new class that inherits from the CUITe SilverlightComboBox but when trying to use 'Find' and 'By' to define a ComboBox control I get the following error: System.ArgumentException: No constructor for type 'CUITe.Controls.SilverlightControls.Custom.SilverlightComboBox' contains arguments in the following order:
  1. By - Search configuration

**Comment by icnocop** [comment]
To support inheriting from SilverlightComboBox, you'll probably need to have a constructor signature as follows:

```
public MySilverlightComboBox(UITestControl parent, By searchConfiguration = null)
            : base(parent, searchConfiguration)
        {
        }
```

You can also try to use [Extension Methods](https://msdn.microsoft.com/en-us//library/bb383977.aspx).
