### ISSUE TITLE
Application response issues through cuite framework.

### ISSUE THREAD

**Issue by Sonal-choudhary** [icnocop/cuite#107]
Hi All,
I recently faced an issue while working on CUITe framework.
There is a continuous progress(or loading) seen while my framework clicks on any button in the application, sometimes even it resulted in Timeout, Although when we try to click the same button manually it gets loaded quite quickly and the application response is proper.
Can anyone help me in this regard, or someone did face this ever??
Thanks,
Sonal

**Comment by icnocop** [comment]
Can you isolate and share your code to just the part that programmatically clicks on the button?
