### ISSUE TITLE
By.SearchProperty loses property name when dash is included

### ISSUE THREAD

**Issue by javelinco** [icnocop/cuite#110]
We are attempting to use the `browserWindow.Find<HtmlHyperlink>(By.SearchProperties("data-id=12345"));` functionality, and we are running into a problem where the property name seems to be truncated to "id" (in the case of the example).

Should SearchProperties be able to find any attribute name/value pair?  Or is this function intended for different usages?

You can see this behavior by modifying the "ClickAllControlsOnPage_UsingReflection_Succeeds()" function in the Sut.HtmlTest.HtmlControlTests class.  Add the property "data-id" to the button control, with a value of "12345", and then modify the following line: `ControlBase a = browserWindow.Find<HtmlHyperlink>(By.SearchProperties("data-id=12345"));`

Please let me know if you need further details.

**Comment by FantasticFiasco** [comment]
I've verified it.

It doesn't seem to be related to `SearchPropertiesConfigurator`, that class works as intended and respects the dash. The name is passed correctly to CUIT, but CUIT is perhaps parsing it again.

@icnocop Have you seen this before?

**Comment by javelinco** [comment]
Good point - I apologize for not mentioning that I had not seen the problem in the SearchPropertiesConfigurator tests.  I did try to track it down to a source, but was not able to find where it was getting parsed out.

**Comment by icnocop** [comment]
This works for me:
```
    [TestMethod]
    public void ClickButtonWithDataIdAttribute_UsingFilterPropertiesAndControlDefinition_Succeeds()
    {
        using (var webPage = new TempWebPage(
@"<html>
    <head>
        <title>test</title>
    </head>
    <body>
        <button data-id=""12345"">test</button>
    </body>
</html>"))
            {
                var browserWindow = BrowserWindow.Launch(webPage.FilePath);
                
                HtmlButton button = browserWindow.Find<HtmlButton>();

                button.SourceControl.FilterProperties.Add(
                        CUITControls.HtmlControl.PropertyNames.ControlDefinition,
                        "data-id=\"12345\"");
                button.Click();
            }
        }
```
I was able to record the click action on the button using Visual Studio's Coded UI test recorder and it used `FilterProperties` and `ControlDefinition` to identify the control.
