### ISSUE TITLE
When will there be a general availability release? 

### ISSUE THREAD

**Issue by grock90** [icnocop/cuite#112]
Currently the nuget package is still beta, I'm curious what are the plans for general availability and a non-beta status?

**Comment by FantasticFiasco** [comment]
Yes, the plan is to release v2.0. I think documentation is the final piece of the puzzle, but unfortunately we haven't got around to write it.

**Comment by grock90** [comment]
Do you anticipate this to occur in Q1 or another quarter this year?

**Comment by FantasticFiasco** [comment]
It is really hard to tell. But I would argue that whether or not CUITe was generally available or not should not stopping you from using it. An official 2,0 version would be the same code as we have now, nothing important other than documentation would be different.

**Comment by icnocop** [comment]
2.1 has been released.
