### ISSUE TITLE
Cannot address elements in TabControl

### ISSUE THREAD

**Issue by GHapps** [icnocop/cuite#113]
My platform: Win 7 Pro x64, VS 2015 Enterprise

I have created a sample of my issue [here](https://github.com/GHapps/CuiteTabSample)

I have been experimenting with writing CUITe tests with WPF tab controls with the framework. 
When I try to get the framework to 'click' a button in a tab control, the test fail with the exception:

`Microsoft.VisualStudio.TestTools.UITest.Extension.UITestControlNotFoundException: The playback failed to find the control with the given search properties. Additional Details: 
TechnologyName:  'UIA'
FrameworkId:  'Wpf'
ControlType:  'Button'
AutomationId:  'ZybHF6Q6IEe-4FJCaqgC6w'
 Search may have failed at '' TabList as it may have virtualized children. If the control being searched is descendant of '' TabList then including it as the parent container may solve the problem. ---> System.Runtime.InteropServices.COMException: Error HRESULT E_FAIL has been returned from a call to a COM component.`

It seems as though the framework cannot find the control, by automation Id or name. However, a simple regular CUIT test can address the components in the tab. 

Not sure if I'm just not using the framwork correctly, but a standard CUIT test will be able to address the button and click it by using the standard VS2015 code generator.

Any help appreciated.

MainWindow.xaml
```xml
<Window x:Class="CuiteTabSample.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:CuiteTabSample"
        mc:Ignorable="d"
        Title="MainWindow" Height="350" Width="525">
    <Grid>
        <TabControl Name="MainTabControl">
            <TabItem Header="General">
                <Button Content="Notify" AutomationProperties.AutomationId="ZybHF6Q6IEe-4FJCaqgC6w" Name="NotifyButton" ContentStringFormat=""  VerticalAlignment="Top" HorizontalAlignment="Left" />
            </TabItem>
            <TabItem Header="Security" />
            <TabItem Header="Details" />
        </TabControl>

    </Grid>
</Window>
`
CodedUI test:


`c#
[TestMethod]
        public void CodedUITestMethod1()
        {
            // To generate code for this test, select "Generate Code for Coded UI Test" from the shortcut menu and select one of the menu items.
            ApplicationUnderTest.Launch(@"C:\git\CuiteTabSample\CuiteTabSample\bin\Debug\CuiteTabSample.exe");

            WpfWindow window = new WpfWindow(By.Name("MainWindow"));          

            WpfTabList tabCollection = window.Find<WpfTabList>(By.Name("MainTabControl"));
            WpfTabPage tab = tabCollection.Find<WpfTabPage>(By.Name("General"));

            tab.Click();
            WpfButton notifyButton2 = tab.Find<WpfButton>(By.AutomationId("ZybHF6Q6IEe-4FJCaqgC6w"));
            notifyButton2.Click();
        }
`

**Comment by icnocop** [comment]
I was able to use Visual Studio's Coded UI Test Recorder and found a difference between the code it generated and the code you provided.

Change this:
`WpfTabList tabCollection = window.Find<WpfTabList>(By.Name("MainTabControl"));`
to this:
`WpfTabList tabCollection = window.Find<WpfTabList>(By.AutomationId("MainTabControl"));`

Once I made this change, playback worked as expected.

**Comment by GHapps** [comment]
Ahh yes, this did work fine and the button is indeed now clicked. Than you for looking into this.

One additional thing I found though is that when I went to assess the visibility of various components, they seem to be reported incorrectly?

I have updated my test project [here](https://github.com/GHapps/CuiteTabSample)

In the code sample below the assertion at the end fails even though the textbox becomes clearly visible on screen after the click event. Is this the correct behavior or is there some other check I should be making?

```C#
            WpfText textbox = tab.Find<WpfText>(By.AutomationId("5-1IoR3tekinspUsj8I_LQ"));
            Assert.IsFalse(textbox.Visible);

            WpfButton notifyButton2 = tab.Find<WpfButton>(By.AutomationId("ZybHF6Q6IEe-4FJCaqgC6w"));
            notifyButton2.Click();

            //SHould now show (but it reports as not visible, when it is in fact visible on the screen)
            //so this assertion erroneously fails:
            Assert.IsTrue(textbox.Visible);

**Comment by icnocop** [comment]
If the Visual Studio Coded UI Test Recorder can't see your control, then CUITe will probably also have a hard time finding it. ;)

See this article for an explanation and work-around:
http://www.colinsalmcorner.com/post/genericautomationpeer--helping-the-coded-ui-framework-find-your-custom-controls
