### ISSUE TITLE
Name of controls

### ISSUE THREAD

**Issue by FantasticFiasco** [icnocop/cuite#12]
I would really love to change the prefix of the controls from _CUITe_ to _Enhanced_. It means for instance that _CUITe_HtmlButton_ would be called _EnhancedHtmlButton_.

I realize that renaming all controls would break backward compatibility, and I realize the severity of it. But the current naming format  with using the prefix _CUITe_ with the underscore after is looking rather odd in C# and is breaking [Microsoft guidelines](https://msdn.microsoft.com/en-us/library/ms229002%28v=vs.110%29.aspx).

In the _General Naming Conventions_ section one can read:
_DO NOT use underscores, hyphens, or any other nonalphanumeric characters._
_DO NOT use any acronyms that are not widely accepted, and even if they are, only when necessary._

What is your take on the issue?

**Comment by icnocop** [comment]
I agree that the code should follow Microsoft's coding guidelines.

I'm wondering if we can just use HtmlButton without a prefix?

The classes can still be differentiated by using the CUITe.Controls.HtmlControls namespace and shouldn't conflict with the Microsoft.VisualStudio.TestTools.UITesting.HtmlControls namespace for example.

**Comment by FantasticFiasco** [comment]
I'm starting to like you :-)

As long as we don't anticipate CUITe consumers getting confused with which control they are using I think it is a really good idea.
But perhaps the confusion about the two controls is more of an issue for us then it is to the consumers. We would have to reference both controls but consumers only references the CUITe version.
