### ISSUE TITLE
How to work with multiple tab in IE 11 using Cuite

### ISSUE THREAD

**Issue by ChetanBaraskar** [icnocop/cuite#120]

**Comment by icnocop** [comment]
CUITe doesn't have any specific logic to work with IE's tabbed browsing.

CUITe is based on Microsoft's Coded UI technology.

If you can interact with multiple tabs using Coded UI then it should be straight forward.

For example, try running the Coded UI Test Recorder and record mouse clicks on the tabs to mimic your automated test and look at the code it generates.

Another approach is to use the keyboard to switch between tabs.
This can be done using `Keyboard.SendKeys` for example in the Coded UI test.

**Comment by cb01** [comment]
Thanks for the suggestion.

I choose the approach of keyboard to switch between tabs
