### ISSUE TITLE
Chrome is not working for Visual Studio 2013 using cuite

### ISSUE THREAD

**Issue by cb01** [icnocop/cuite#121]
I am using Visual studion 2013 and to automate tests I am using Cuite framework "CUITe.VS2013.2.0.392-beta" to recognize object.

Everything Is working fine If i run automated test with IE, but it is not working in Chrome browser.

I have also install Selenium components for Coded UI Cross Browser Testing, but only the browser get opened and get close.

Could anyone please suggest how I should run my test on Chrome

**Comment by icnocop** [comment]
What error message appears in the output?
