### ISSUE TITLE
How to add multiple search properties for a control, using CUITe framework ?

### ISSUE THREAD

**Issue by pragnyabiswas** [icnocop/cuite#122]
Tried adding 2 arguments in the "By" clause, but that's not the correct syntax. Please help me know the correct one.

Example:-
ParentWindow.Find<WpfButton>(By.Name("ABC"), By.Id("DEF")).Click();

**Comment by icnocop** [comment]
Hi.

`ParentWindow.Find(By.Name("ABC").AndId("DEF")).Click();`

Here are some more examples:
https://github.com/icnocop/cuite/blob/master/src/CUITeTest/SearchConfigurations/ByTest.cs

Thank you.

**Comment by pragnyabiswas** [comment]
Thanks for the prompt reply.
