### ISSUE TITLE
Issues with horizontal scrolling in WPF application

### ISSUE THREAD

**Issue by pragnyabiswas** [icnocop/cuite#123]
I wanted to scroll the horizontal scrollbar to the right in a window till the position of the ‘footerColumn’ column of a Table. Then, encode a value in a textbox.

For that I tried the following and faced these issues:-
 
1)  `ABC.EnsureClickable(); // ‘ABC’ is of ‘WpfEdit’ type. `
      
       ABC is the textbox in the ‘footerColumn’ column of a Table.
       The above code snippet took almost 3 mins to complete.
       Is there any workaround for this ?
 
2) `HScrollBar.SetProperty("Position", HScrollBar.GetProperty("MaximumPosition")); `
     `// Works - HscrollBar is of WpfScrollBar type.`

    `HScrollBar.SetProperty("Position", footerColumn.GetProperty("Left"));`
    `// Didnot work – footerColumn is of WpfCustom type`

    `HScrollBar.SetProperty("Position", (WpfScrollBar)(footerColumn.GetProperty("Left")));` 
    `// Type-casting didnot work.`

     Here, the the 2nd parameter for SetProperty should return the same type as the control calling it 
     (Correct me if I’m wrong).
     That’s why the 1st code snippet in this point worked and not the 2nd one.
      Again type-casting didn’t work.
      Is there a way to encode 2nd parameter dynamically ?

I'm new to Coded UI and CUITe framework. Thanks in advance for providing solution.

**Comment by icnocop** [comment]
1.
I recommend enabling the Coded UI test logs and see what is taking so long.

As a result of examining the logs, you may find that you can try setting one ore more Coded UI playback options and/or maybe limit the scope of searching for the control to improve performance.

The `EnsureClickable` method just calls `EnsureClickable` on the underlying control.

This doesn't seem to be an issue related to CUITe.

https://docs.microsoft.com/en-us/visualstudio/test/analyzing-coded-ui-tests-using-coded-ui-test-logs?view=vs-2017
https://blogs.msdn.microsoft.com/devops/2012/01/31/guidelines-on-improving-performance-of-coded-ui-test-playback/

2.
I'm not exactly sure what you're trying to do.

If `HScrollBar` is a `WpfScrollBar`, then you can try setting its position by calling `HScrollBar.Position = 100;` for example.

You can also try to record your actions using Visual Studio's Coded UI Test Recorder and then analyze the generated code.

This doesn't seem to be an issue related to CUITe.

I recommend asking your questions in the Visual Studio UI Automation Testing forum: https://social.msdn.microsoft.com/Forums/en-US/home?forum=vsautotest
