### ISSUE TITLE
FindMatchingControls() and GetContent() for WpfControls

### ISSUE THREAD

**Issue by pragnyabiswas** [icnocop/cuite#124]
Please let me know the corresponding method/function for **FindMatchingControls() and GetContent() for WpfControls** available in CUITe.

**Comment by icnocop** [comment]
Hi.

You can use the `SourceControl` property to get the underlying `UITestControl`.

And then you can call `FindMatchingControls` on that object.

The same applies to `GetContent`.

Thank you.
