### ISSUE TITLE
Can we use playback class to generate text file containing CodedUI test logs instead of HTML file. If not what are the other methods to do that? 

### ISSUE THREAD

**Issue by Afsah-k** [icnocop/cuite#125]

**Comment by icnocop** [comment]
CUITe uses Microsoft's Coded UI Test and doesn't implement it's own logging mechanism.

See this post in Microsoft's `Visual Studio Development` > `Visual Studio Unit Testing` forum [How to create the custom HTML report using CODEDUI?](https://social.msdn.microsoft.com/Forums/vstudio/en-US/9d41a992-064d-4e17-9969-6aae7e2a03bf/how-to-create-the-custom-html-report-using-codedui-?forum=vsunittest)

Hope that helps.

For reference, the question was cross-posted in multiple places:
https://github.com/MicrosoftDocs/visualstudio-docs/issues/4881
https://github.com/MicrosoftDocs/visualstudio-docs/issues/4882
