### ISSUE TITLE
Obsolete methods

### ISSUE THREAD

**Issue by FantasticFiasco** [icnocop/cuite#26]
There are some methods that are marked as obsolete, for instance in `BrowserWindowUnderTest`. Do you have any plans when we can remove those? Would it be appropriate for me to remove them during my refactoring of the `ControlBase` classes?

**Comment by icnocop** [comment]
Yes, the obsolete methods can be removed since we've upgraded the major version number of CUITe and we're already not backward compatible. Thank you.
