### ISSUE TITLE
'By' syntax used in Selenium

### ISSUE THREAD

**Issue by FantasticFiasco** [icnocop/cuite#27]
What are your thought regarding the `By` syntax used in Selenium. Examples can be found [here](http://www.codeproject.com/Articles/1015893/Microsoft-Edge-WebDriver-What-Everybody-Ought-to-K).

The syntax of `searchProperties` in CUITe is pretty advanced in my opinion. When first introduced with the syntax I was confused with what to write there. Developers new to CUITe might find it easier to start using CUITe if there existed a `By` class that help with defining search properties.

Of course there should also be a method on the `By` class that lets developers write search properties in the compressed syntax currently supported.

**Comment by icnocop** [comment]
I like the `By` syntax and don't mind if the current syntax changes or gets expanded.

Thank you.
