### ISSUE TITLE
Fix tests in 'CUITe for .NET v4.5 (VS2013)' solution

### ISSUE THREAD

**Issue by FantasticFiasco** [icnocop/cuite#3]
There are tests failing in the solution called _CUITe for .NET v4.5 (VS2013)_. I will fix the once relating to WPF but there are about 19 tests that fail in _Sample_CUITeTestProject_. I can only assume that I haven't got the same environment as you do? Are we running the tests on different versions of IE?

Can you verify that the tests work on your machine?

**Comment by icnocop** [comment]
What error messages do you get when you try to run them?

Thank you.

**Comment by FantasticFiasco** [comment]
I've created a zip with the failed coded UI test results. The zip can be downloaded from [here](https://dl.dropboxusercontent.com/u/5415889/CUITe_FailedTests.zip). I would like to note that the most probable root of the problem is me :-) But I've installed the Silverlight UI Test plugin, but perhaps I haven't installed all Silverlight SDKs I ought to?

**Comment by FantasticFiasco** [comment]
Bump

**Comment by icnocop** [comment]
Thank you.

I just fixed some of those failing tests.

I am running on Windows 7 Enterprise x64 SP1 with Internet Explorer 11.0.9600.17843.

In order to run cross browser tests (ex. SetText_OnHtmlEditUsingChrome_Succeeds and SetText_OnHtmlEditUsingFirefox_Succeeds), the "Selenium components for Coded UI Cross Browser Testing" must be installed.
https://visualstudiogallery.msdn.microsoft.com/11cfc881-f8c9-4f96-b303-a2780156628d
The error message includes a link that will automatically download the msi.

I'm not sure why the test "GetHtmlDocument_FromBrowserWindow_CanGetOuterHtmlProperty" is failing for you with the error message:
`Assert.AreEqual failed. Expected:<<body>>. Actual:<<body >.`
Did you make any code changes to TestHtmlPage.html?

**Comment by FantasticFiasco** [comment]
I am running Windows 7 Professional x64 SP1 with Internet Explorer 11.0.9600.17914.

Your checkin fixed some of my failing tests, I am down to ~8. I will look into the failing tests tonight. About the test _GetHtmlDocument_FromBrowserWindow_CanGetOuterHtmlProperty_, _doc.UnWrap().GetProperty("OuterHtml").ToString()_ has the following value when I run the test:

```
<body vsttFireTimer=\"false\">\n<div id=\"calculatorContainer1\">\n....
```

Please note that _vsttFireTimer_ isn't a part ot the HTML in _TestHtmlPage.html_, i.e. I haven't changed that file.

**Comment by FantasticFiasco** [comment]
I'm now down to 7 failing tests, and one of them is surely that I don't have Firefox installed. Nevertheless, I am not planning to investigate the issues further since the bulk of my contributions will be on the WPF side of things in CUITe. I was just surprised that I had failing tests and thought I was the responsible one, but now see that I'm not.

**Comment by icnocop** [comment]
I'm not sure why vsttFireTimer is being injected in the HTML file as I could not find any documentation on it whatsoever. :(

**Comment by FantasticFiasco** [comment]
I came across the term _vstt_ when browsing through a Visual Studio project file, it was in the following context:

```
<ReferencePath>$(ProgramFiles)\Common Files\microsoft shared\VSTT\$(VisualStudioVersion)\UITestExtensionPackages</ReferencePath>
```

According to this [link](http://www.acronymfinder.com/Visual-Studio-Team-System-for-Testers-%28automated-testing-tool%29-%28VSTT%29.html) _VSTT_ stands for _Visual Studio Team System for Testers_. No idea why the term gets injected in the HTML though.

**Comment by FantasticFiasco** [comment]
Out of curiosity, do all tests pass on the CI?

**Comment by icnocop** [comment]
The latest build fails when trying to run the test target after running the build target:
https://ci.appveyor.com/project/icnocop/cuite

```
Build FAILED.

"C:\projects\cuite\src\build.proj" (Test target) (1) ->
(Test target) -> 
  EXEC : error : The test source file "Sample_CUITeTestProject_WinControls\bin\Release\Sample_CUITeTestProject_WinControls.dll" provided was not found. [C:\projects\cuite\src\build.proj]
  EXEC : error : The test source file "Sample_CUITeTestProject_WpfControls\bin\Release\Sample_CUITeTestProject_WpfControls.dll" provided was not found. [C:\projects\cuite\src\build.proj]
  C:\projects\cuite\src\build.proj(72,5): error MSB3073: The command ""%VSINSTALLDIR%Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" Sample_CUITeTestProject\bin\Release\Sample_CUITeTestProject.dll Sample_CUITeTestProject_WinControls\bin\Release\Sample_CUITeTestProject_WinControls.dll Sample_CUITeTestProject_WpfControls\bin\Release\Sample_CUITeTestProject_WpfControls.dll" exited with code 1.

    0 Warning(s)
    3 Error(s)
```

**Comment by icnocop** [comment]
The test that fails because of the `vsttFireTimer` attribute being injected in the `body` element is because of the MOTW in the html file.

I've updated the test to take this into consideration in commit 24871ef1a01f4373590e9184b871ed93db553081.

**Comment by FantasticFiasco** [comment]
Being a desktop application developer this was the first time I heard about _Mark of the Web_. Interesting reading though. Pretty impressed that you found the solution, since `vsttFireTimer` turned up almost nothing on a Google search.

**Comment by icnocop** [comment]
I was able to automatically install the required dependencies before the build:
1. Microsoft Visual Studio 2013 Coded UI Test Plugin for Silverlight
2. Google Chrome
3. Mozilla Firefox 27.0.1
4. Selenium components for Coded UI Cross Browser Testing

But there are still some issues with Internet Explorer's security, that the MOTW does not resolve, as indicated in the screenshot from this sample test log:
https://ci.appveyor.com/api/buildjobs/10j8ni4k7ectyi7p/artifacts/appveyor_APPVYR-WIN20122%202015-08-27%2017_07_51/In/76a1e464-186b-4cd1-b57b-a52fc6678cb8/APPVYR-WIN20122/UITestActionLog.html

I will have to do some more investigation, as I'm thinking it's specific to Windows Server 2012 R2 (x64).

**Comment by FantasticFiasco** [comment]
Still, you've come a long way. Nice work!
Please let me know if there is anything I can do to help you with your problems.

**Comment by icnocop** [comment]
I fixed the tests I could more easily fix.

I added the `Ignore` attribute on those that will take some more time to diagnose and fix as I am getting mixed behavior on my Windows 7 machine and the Windows Server 2012 R2 build agent.

You've done some great work too!

Thank you.
