### ISSUE TITLE
Update ObjectRecorder to utilize new static class "By"

### ISSUE THREAD

**Issue by Kritner** [icnocop/cuite#36]
The object recorder is still using the old syntax 

```
new HTMLControlType("Id=MyControlIdName");
```

rather than the new syntax (Example)

```
new HTMLControlType(By.Id("MyControlIdName"));
```

**Comment by FantasticFiasco** [comment]
I will get right on it. Sorry for the inconvenience.

**Comment by Kritner** [comment]
No big deal.  Honestly I don't use the object recorder much - usually write our my elements by hand.  I Just noticed it was a potential miss from when the syntax was changed, so figured I'd put in an issue.

**Comment by FantasticFiasco** [comment]
You where right to do so. I think I have to add some mechanism, unit test or something, that validates that this doesn't slip through again.

**Comment by FantasticFiasco** [comment]
Thanks for the reported issue, it should now be fixed.
