### ISSUE TITLE
Preparation for 2.0 release

### ISSUE THREAD

**Issue by FantasticFiasco** [icnocop/cuite#40]
The following items have to be addressed before releasing CUITe 2.0:
- Remove _Pre_ from NuGet package
- Perhaps mentioning the prerequisites in the NuGet description to prevent developers to install the package when they are using the wrong version or edition of Visual Studio.
- Perhaps open a readme describing the prerequicites after NuGet is installed, i.e. the extra requirements for HTML and Silverlight testing
- Create a complete Wiki describing the state of 2.0
- ~~Create a document where we describe the changes (new features, bug fixes and so on) between each version~~ DONE

Anything else you can think of?

**Comment by icnocop** [comment]
The only other thing I can think of is having a set of specific test cases for testing nuget packages and their integration with each version of Visual Studio we support and the expectations. These could just be simple hand-written tests that are manually run and then possibly automated at a later time.

**Comment by icnocop** [comment]
Oh, and also integration test cases for the Object Recorder.

**Comment by FantasticFiasco** [comment]
Yes, some sort of tests for the Object Recorder seems important. Perhaps a refactoring of the codebase as well, making it more testable.

**Comment by icnocop** [comment]
2.1 has been released.

We'll plan to tackle issues if/when they arise.
