### ISSUE TITLE
Improvements to WinForms Search

### ISSUE THREAD

**Issue by thePantz** [icnocop/cuite#47]
CUITe is lacking in support for WinForms as mentioned in PR #20 

In CodedUI the unique identifying property for WinForms is 'ControlName'.

Most inspection tools such as UIA Verify will see this value as AutomationId but CodedUI gives it a different name in this case.

I would like to add a ControlName configurator and modify the By object so that users can take advantage of this search property.

**Comment by FantasticFiasco** [comment]
I started working on [this specific feature](https://github.com/FantasticFiasco/cuite/tree/winforms-control-name) some time ago. I'm done with the implementation but the only thing stopping me from doing a pull request is that a few tests fail, and other stuff got higher priority.

**Comment by thePantz** [comment]
Perfect! That's exactly what I'm looking for
