### ISSUE TITLE
No class for HTML <strong> tag?

### ISSUE THREAD

**Issue by josephville** [icnocop/cuite#49]
The previous version had the class CUIT_HtmlStrong. In version 2, I don't see an HtmlStrong class. Has this functionality been removed, or relocated?

**Comment by FantasticFiasco** [comment]
I don't see it in the latest version of the code on CodePlex either. Was it removed before moving to GitHub?

**Comment by icnocop** [comment]
Which previous version of CUITe do you see support for the `<strong>` tag?

Thank you.

**Comment by josephville** [comment]
Thanks for the quick response.  I saw support for the tag in version
1.0.6.0.

**Comment by icnocop** [comment]
I don't see any support for it in the 1.0.6.0 beta release on codeplex.

![cuite_htmls](https://cloud.githubusercontent.com/assets/507649/11640251/736ccc52-9ce6-11e5-8445-bb155151e19b.GIF)

Can you send me a screenshot of what you see please?

Was it a class you created yourself that inherited from `CUITe_HtmlCustom` for example?

Thank you.

**Comment by josephville** [comment]
I did not write that code, it must have been written by someone else who
was previously on my team. I just saw that it was listed with the other
Html Controls and thought it was part of the package. It's as you said:
it's a class inherited from CUITe_HtmlCustom.  Thanks anyway and sorry for
the confusion.

[image: Inline image 2]

**Comment by FantasticFiasco** [comment]
It seems that this issue was solved, can I close the issue?
