### ISSUE TITLE
'Get' method renamed to 'Find', but I don't see 'Find' in BrowserWindowUnderTest

### ISSUE THREAD

**Issue by josephville** [icnocop/cuite#52]
The changelog says the 'Get' was renamed to 'Find', but the only 'Find' method I see which accepts generic type parameters is in UITestControlExtensions. But this changes some functionality. Has the support changed in more ways than specified in the changelog?

Thanks.

**Comment by FantasticFiasco** [comment]
The method not only changed name but also functionality in the way you can specify what to find. It started with [issue 27](https://github.com/icnocop/cuite/issues/27) that became [pull request 29](https://github.com/icnocop/cuite/pull/29).

All this will be documented in the Wiki for the official 2.0 release, but we are currently not there. Please let me know if there is anything you feel is missing or don't understand, and I'll make sure that it will be straightened out.

**Comment by FantasticFiasco** [comment]
Did you find the `Find<T>` method to suite your needs, and if so can I close the issue?
