### ISSUE TITLE
CUITe NuGet package only contains VS2013\net40\CUITe.dll and fails to work in VS2010

### ISSUE THREAD

**Issue by icnocop** [icnocop/cuite#53]
CUITe NuGet package only contains VS2013\net40\CUITe.dll and fails to work in VS2010.

**Comment by FantasticFiasco** [comment]
I'll try to take a look at it tonight.

**Comment by FantasticFiasco** [comment]
When I run `Build.bat` it produces the following NuGet packages:
- CUITe.2.0.0-beta.nupkg
- CUITe.Silverlight.VS2010.2.0.0-beta.nupkg
- CUITe.Silverlight.VS2012.2.0.0-beta.nupkg
- CUITe.Silverlight.VS2013.2.0.0-beta.nupkg

Assuming we are talking about the first package. It contains the following libraries:
- net40\CUITe.dll
- net45\CUITe.dll

I think those are the only .NET versions we support. VS2010 only supports .NET4.0, am I correct?

Then we have _install.ps1_ in the NuGet package that adds binding redirects to the _app.config_ file. This means that if we assume that VS2010 is having a CUIT project in .NET4.0, when installing CUITe we add binding redirects to the VS2010 versions of the references.

Are you sure that the NuGet package you are seeing only contains one _CUITe.dll_?

**Comment by icnocop** [comment]
Sorry, I should have been more descriptive.

Steps to reproduce:
1. Create a new Visual Studio 2010 solution.
    I'm using Windows 7 Home Premium 64-bit
    Visual Studio 2010 SP1
2. Add a new test project targeting the .net 4.0 framework
3. Add a new coded UI test (Cancel the code generation wizard)
4. Install the CUITe nuget package (Using Install-Package and my local development path as the source)
5. Add a new coded UI test class that uses CUITe.Controls.HtmlControls for example
6. Build the solution
The build fails with the following output:

```
------ Rebuild All started: Project: TestProject, Configuration: Debug Any CPU ------
error CS1705: Assembly 'CUITe, Version=2.0.0.0, Culture=neutral, PublicKeyToken=a67a8fd362ae8334' uses 'Microsoft.VisualStudio.TestTools.UITesting, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'Microsoft.VisualStudio.TestTools.UITesting, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
error CS1705: Assembly 'CUITe, Version=2.0.0.0, Culture=neutral, PublicKeyToken=a67a8fd362ae8334' uses 'Microsoft.VisualStudio.TestTools.UITest.Extension, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'Microsoft.VisualStudio.TestTools.UITest.Extension, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

Compile complete -- 2 errors, 0 warnings
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3247: Found conflicts between different versions of the same dependent assembly.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

Build Summary
-------------
00:02.649 - Failed  - Debug Any CPU - TestProject\TestProject.csproj

Total build time: 00:10.023

========== Rebuild All: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========
```

The app.config has the expected changes, but the assembly binding redirects do not include 12.0 as an "old" version:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.VisualStudio.TestTools.UITest.Extension" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="10.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.VisualStudio.TestTools.UITesting" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="10.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

This is because the CUITe.dll that is included in the nuget package was built with an explicit reference to "Microsoft.VisualStudio.TestTools.UITesting, Version=12.0.0.0".

I think it's best if we "revert" back to having a nuget package for each version of Visual Studio to avoid this issue.

**Comment by FantasticFiasco** [comment]
It could be that there is a bug in the `app.config.install.xdt` of the NuGet package. In theory the `assemblyIdentity` part of the _app.config_ file should be replaced with this when installing the package:

```
<assemblyIdentity name="Microsoft.VisualStudio.TestTools.UITest.Extension" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
<bindingRedirect oldVersion="10.0.0.0-14.0.0.0" newVersion="[Placeholder]"/>
```

But since `oldVersion` is `0.0.0.0-10.0.0.0`, I assume that the assembly redirect wasn't replaced when installing the NuGet package. Can we verify that `oldVersion` was `0.0.0.0-10.0.0.0` even before installing the package.

In the end you are the boss, you decide.

**Comment by icnocop** [comment]
Before installing the NuGet package, app.config doesn't exist.

**Comment by icnocop** [comment]
Even if I manually update app.config as follows:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.VisualStudio.TestTools.UITest.Extension" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="10.0.0.0-14.0.0.0" newVersion="10.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.VisualStudio.TestTools.UITesting" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="10.0.0.0-14.0.0.0" newVersion="10.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

I still get the same error.

app.config is only used during runtime and not compile time, and the error is during compile time.

Similar errors occur when using Visual Studio 2012 as well.

I will do some more testing and submit a pull request.

Thank you.

**Comment by icnocop** [comment]
I created pull request https://github.com/icnocop/cuite/pull/54.
I contains some automation for testing the steps required to install the CUITe NuGet package in a Coded UI test project in Visual Studio 2010+, but there are some caveats:
1. When viewing the Package Manager Console, the test arbitrarily waits for 5 seconds for it to load and this may not be enough time and so it may cause the test to fail.
2. When running all tests in the solution, the test arbitrarily waits for 30 seconds for them to complete, which may not be enough time, and also there's no checking to see if the tests passed or failed so this becomes a manual step.
3. Testing with Silverlight is not yet implemented.

**Comment by icnocop** [comment]
I could not find a nice way to support multiple versions of Visual Studio with just one NuGet package. It would have required the NuGet package to become unconventional and require some hackery which I don't think is a good approach.

**Comment by FantasticFiasco** [comment]
I agree, it looks like you did a good job. I will look into SpecFlow later.

**Comment by icnocop** [comment]
Fixed per commit https://github.com/icnocop/cuite/commit/e0557613ec01bba290d2eab27d9eeb7c55f664d3
