### ISSUE TITLE
Trouble getting instance of Object Repository from BrowserWindowUnderTest

### ISSUE THREAD

**Issue by Kritner** [icnocop/cuite#57]
I'm sure I'm doing this incorrectly, but I'm not finding a whole lot on a tutorial on how to go about accomplishing a multi page test.  I had this working previous with the older syntax (codeplex's version) but am having trouble with the current syntax.

```
public class Foo
{
    public void System_Login(string URL, string UserID, string Password, string System)
    {
        BrowserWindow bw = BrowserWindowUnderTest.Launch(URL);
        LogInPage pgLogin = BrowserWindowUnderTest.GetBrowserWindow<LogInPage>();
        pgLogin.txtUserID.Text = UserID;
        pgLogin.txtPassword.Text = Password;
        pgLogin.cboSystem.SelectItem(System);
        pgLogin.btnLogin.Click(); // Directs to "NewPage"

        DoStuff();
    }

    public void DoStuff()
    {
         NewPage newPage = BrowserWindowUnderTest.GetBrowserWindow<NewPage>();
    }
}

public class LogInPage : BrowserWindowUnderTest
{
    public LogInPage() : base("Log-In Page")
    {
    }

    public HtmlEdit txtUserID
    {
        get
        {
            return this.Find<HtmlEdit>(By.Id("text1"));
        }
    }
    public HtmlPassword txtPassword
    {
        get 
        {
            return this.Find<HtmlPassword>(By.Id("password1"));
        }
    }
    public HtmlComboBox cboSystem
    {
        get
        {
            return this.Find<HtmlComboBox>(By.Id("cboSystem"));
        }
    }
    public HtmlInputButton btnLogin
    {
        get
        {
            return this.Find<HtmlInputButton>(By.Id("submit1"));
        }
    }

}
```

I get a successful compile, but I'm getting an exception when attempting to resolve my `LoginPage` from `LogInPage pgLogin = BrowserWindowUnderTest.GetBrowserWindow<LogInPage>();`

The exception is:

> Test Name:    SmokeTest_DEV
> Test Outcome:   Failed
> Result Message: 
> Test method SmokeTest.CodedUITest1.SmokeTest_DEV threw exception: 
> System.MissingMethodException: Constructor on type 'SmokeTest.ObjectRepository.LogInPage' not found.
> Result StandardOutput:  
> Debug Trace:
> V, 2888, 14, 2015/12/30, 11:56:29.406, 2335822818100, QTAgent32.exe, ConstructDeviceToDriveMap() Added mapping '\Device\Mup\' -> '\'
> V, 2888, 14, 2015/12/30, 11:56:29.406, 2335822818743, QTAgent32.exe, ConstructDeviceToDriveMap() Added mapping '\Device\RdpDr\' -> '\'
> V, 2888, 14, 2015/12/30, 11:56:29.406, 2335822819210, QTAgent32.exe, ConstructDeviceToDriveMap() Added mapping '\Device\LanmanRedirector\' -> '\'
> V, 2888, 14, 2015/12/30, 11:56:29.406, 2335822819692, QTAgent32.exe, ConstructDeviceToDriveMap() Added mapping '\Device\WebDavRedirector\' -> '\'
> V, 2888, 14, 2015/12/30, 11:56:29.406, 2335822824667, QTAgent32.exe, ConstructDeviceToDriveMap() Added mapping '\Device\HarddiskVolume2\' -> 'C:\'
> V, 2888, 14, 2015/12/30, 11:56:29.406, 2335822825430, QTAgent32.exe, ConstructDeviceToDriveMap() Added mapping '\Device\CdRom0\' -> 'D:\'
> V, 2888, 14, 2015/12/30, 11:56:29.406, 2335822825960, QTAgent32.exe, ConstructDeviceToDriveMap() Added mapping '\Device\HarddiskVolume3\' -> 'F:\'
> V, 2888, 14, 2015/12/30, 11:56:29.406, 2335822826635, QTAgent32.exe, ConstructDeviceToDriveMap() Added mapping '\Device\LanmanRedirector\;G:0000000000b2612a\DEVFILE\vol3\Data\Common\' -> 'G:\'
> V, 2888, 14, 2015/12/30, 11:56:29.406, 2335822827474, QTAgent32.exe, ConstructDeviceToDriveMap() Added mapping '\Device\LanmanRedirector\;H:0000000000b2612a\devfile\vol3\Home\Rhammett\' -> 'H:\'
> V, 2888, 14, 2015/12/30, 11:56:30.250, 2335825860170, QTAgent32.exe, ExtensionFramework : Assembly resolver trying to resolve Microsoft.VisualStudio.TestTools.UITest.Extension.IE.EventHelper
> V, 2888, 14, 2015/12/30, 11:56:30.250, 2335825863176, QTAgent32.exe, ExtensionFramework : Assembly resolver trying to resolve Microsoft.VisualStudio.TestTools.UITest.Extension.IE.EventHelper

Is my syntax wrong?  Am I doing something else wrong?  My LoginPage does have a public parameterless constructor, not sure why it's throwing an exception on attempting to assign my LoginPage var

**Comment by FantasticFiasco** [comment]
I am currently on vacation but can take a look at this in three days. Is that OK?

**Comment by Kritner** [comment]
No problem - just trying to get a better feel for the new syntax.

**Comment by FantasticFiasco** [comment]
I am party responsible for the new syntax :-)

The wiki is not up to date with the current syntax, but I think reading the unit tests are a good way to get to know it.

**Comment by icnocop** [comment]
`BrowserWindowUnderTest.GetBrowserWindow<T>();` expects a constructor on type `T` which takes a string parameter for the title of the window.

You can either add a string parameter to the constructor or try to combine the `Launch` and `GetBrowserWindow` functions into one call as follows:

```
        LogInPage pgLogin = BrowserWindowUnderTest.Launch<LogInPage>(URL);
```

Thank you.

**Comment by Kritner** [comment]
@icnocop Thanks, I guess I could do that, but wouldn't I then run into the same issue for my second `NewPage newPage = BrowserWindowUnderTest.GetBrowserWindow<NewPage>();` ? I was under the impression that `BrowserWindowUnderTest.Launch` would open a new URL, and my above was actually just an example, I'm actually doing a test with around 10 separate page flows, would I need to do a `Launch` for each of them, and know the URL to each of them in turn?

**Comment by FantasticFiasco** [comment]
@Kritner I would propose taking a look at the `CUITe.ObjectRepository` namespace. It contains a few nifty classes that enables you to make use of the _Object Repository_ pattern when it comes to how you write your UI tests. There is a migration story there, one that you will have to put effort into doing, but I think it will pay off in the end. More information can be read in the closed pull request #44.

Once you've migrated to using the classes in namespace `CUITe.ObjectRepository`, you can then decide if you wan't to take it to a different level by implementing the feature called _Workflows_ in CUITe, a feature that lets you combined a number of actions, like for instance the interaction between your 10 separate pages, into a workflow that can be reused between tests. For more information about workflows please read the information of the closed pull request #46.

**Comment by FantasticFiasco** [comment]
@Kritner Is it OK if we close this issue?

**Comment by Kritner** [comment]
Yeah - thanks
