### ISSUE TITLE
Build for VS 2015 Enterprise?

### ISSUE THREAD

**Issue by matsovef** [icnocop/cuite#60]
I've downloaded and installed the "default" CUITe (with no version specification). I noticed that it's an older build than the others (like CUITe.VS2013) but I guess the one to use for VS 2015.

If so I've a problem with `HtmlTable` in CUITe. Using the following construction in my code

`HtmlCell cell = table.GetCell(i, j);`

I get the following exception:
`The type 'CUITe.Controls.HtmlControls.HtmlCell' contains no public constructor with the following arguments:`
`1. Microsoft.VisualStudio.TestTools.UITesting.HtmlControls.HtmlHeaderCell`
`2. CUITe.SearchConfigurations.By`

For some reason it tries to construct a new `HtmlHeaderCell` instead of a new `HtmlCell`. An error in the package?

**Comment by matsovef** [comment]
Oops! Got it after a good night sleep. Was iterating over all the cells in a table. First row contains `HtmlHeaderCell` objects that cannot be casted to `HtmlCell` objects.

**Comment by FantasticFiasco** [comment]
Nice! Glad we could help *cough cough*
