### ISSUE TITLE
Can't find controls in a wpf window

### ISSUE THREAD

**Issue by aannenko** [icnocop/cuite#61]
**My platform:** WIn 10 Pro x64, VS 2013 Ultimate Update 5

**Main project with the app:**

**MainWindow.xaml**

``` xaml
<Window  x:Class="TestWpfApplication.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="MainWindow" Height="164" Width="256" Name="TestWpfApplication">
    <Grid VerticalAlignment="Top">
        <StackPanel Margin="8">
            <TextBox Name="FirstNameTextBox" Height="23" TextWrapping="Wrap" VerticalAlignment="Top" Width="120" Text="First Name"/>
            <TextBox Name="LastNameTextBox" Height="23" Margin="0,8" TextWrapping="Wrap" Text="Last Name" VerticalAlignment="Top" Width="120"/>
            <Button Name="GreetingsButton"  Content="Say Hey!" VerticalAlignment="Top" Width="75" Margin="0,0,0,8" Click="Button_Click"/>
            <TextBlock Name="GreetingsTextBlock" TextAlignment="Center" TextWrapping="Wrap" Text="You'll see your greeting here"/>
        </StackPanel>
    </Grid>
</Window>
```

**MainWindow.xaml.cs**

``` csharp
using System.Windows;

namespace TestWpfApplication
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            GreetingsTextBlock.Text = "Hi " + FirstNameTextBox.Text + " " + LastNameTextBox.Text;
        }
    }
}
```

**Second project - with tests:**

**MainWindowUiMap.cs**

``` csharp
using CUITe.Controls.WpfControls;
using CUITe.SearchConfigurations;

namespace CodedUITestProject1.UiMap
{
    public class MainWindowUiMap
    {
        private readonly WpfWindow _uiUnderTest;

        public MainWindowUiMap()
        {
            _uiUnderTest = new WpfWindow(By.Name("TestWpfApplication"));
        }

        public string FirstNameTextBox
        {
            get { return _uiUnderTest.Find<WpfEdit>(By.Name("FirstNameTextBox")).Text; }
            set { _uiUnderTest.Find<WpfEdit>(By.Name("FirstNameTextBox")).Text = value; }
        }

        public string LastNameTextBox
        {
            get { return _uiUnderTest.Find<WpfEdit>(By.Name("LastNameTextBox")).Text; }
            set { _uiUnderTest.Find<WpfEdit>(By.Name("LastNameTextBox")).Text = value; }
        }

        public string GreetingsTextBlock
        {
            get { return _uiUnderTest.Find<WpfText>(By.Name("GreetingsTextBlock")).DisplayText; }
        }

        public void ClickSayHeyButton()
        {
            _uiUnderTest.Find<WpfButton>(By.Name("GreetingsButton")).Click();
        }
    }
}
```

**TestMainWindowGreetings.cs**

``` csharp
using System.Threading;
using CodedUITestProject1.UiMap;
using Microsoft.VisualStudio.TestTools.UITesting;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace CodedUITestProject1.Tests
{
    [CodedUITest]
    public class TestMainWindowGreetings
    {
        [TestMethod]
        public void TestGreetings()
        {
            ApplicationUnderTest.Launch(@"D:\Roxton\Documents\Visual Studio 2013\Projects\TestWpfApplication\TestWpfApplication\bin\Debug\TestWpfApplication.exe");
            var uiUnderTest = new MainWindowUiMap();
            Thread.Sleep(1000);
            uiUnderTest.FirstNameTextBox = "John";
            uiUnderTest.LastNameTextBox = "Doe";
            uiUnderTest.ClickSayHeyButton();
            var greetingsTextBlockValue = uiUnderTest.GreetingsTextBlock;
            Assert.AreEqual("Hi John Doe", greetingsTextBlockValue);
        }
    }
}
```

During the execution of the test in the TestMainWindowGreetings class, I'm getting the following exception:

> Test Name:    TestGreetings
> Test FullName:  CodedUITestProject1.Tests.TestMainWindowGreetings.TestGreetings
> Test Source:    d:\Roxton\Documents\Visual Studio 2013\Projects\TestWpfApplication\CodedUITestProject1\Tests\TestMainWindowGreetings.cs : line 13
> Test Outcome:   Failed
> Test Duration:  0:00:07,5583427
> 
> Result Message:  
> Test method CodedUITestProject1.Tests.TestMainWindowGreetings.TestGreetings threw exception: 
> Microsoft.VisualStudio.TestTools.UITest.Extension.UITestControlNotFoundException: The playback failed to find the control with the given search properties. Additional Details: 
> TechnologyName:  'UIA'
> FrameworkId:  'Wpf'
> ControlType:  'Edit'
> Name:  'FirstNameTextBox'
>  Search may have failed at 'TabGroup|ST:0:0:{34e76e81-ee4a-11d0-ae2e-00a0c90ff...' TabList as it may have virtualized children. If the control being searched is descendant of 'TabGroup|ST:0:0:{34e76e81-ee4a-11d0-ae2e-00a0c90ff...' TabList then including it as the parent container may solve the problem. ---> System.Runtime.InteropServices.COMException: Error HRESULT E_FAIL has been returned from a call to a COM component.
> Result StackTrace:  
> at Microsoft.VisualStudio.TestTools.UITest.Playback.Engine.IScreenElement.FindAllDescendants(String bstrQueryId, Object& pvarResKeys, Int32 cResKeys, Int32 nMaxDepth)
>    at Microsoft.VisualStudio.TestTools.UITest.Playback.ScreenElement.FindAllScreenElement(String queryId, Int32 depth, Boolean singleQueryId, Boolean throwException, Boolean resetSkipStep)
>    at Microsoft.VisualStudio.TestTools.UITest.Playback.ScreenElement.FindScreenElement(String queryId, Int32 depth, Boolean resetSkipStep)
>    at Microsoft.VisualStudio.TestTools.UITesting.UITestControl.FindFirstDescendant(String queryId, Int32 maxDepth, Int32& timeLeft)
>  --- End of inner exception stack trace ---
>     at Microsoft.VisualStudio.TestTools.UITesting.Playback.MapControlNotFoundException(COMException ex, IPlaybackContext context)
>    at Microsoft.VisualStudio.TestTools.UITesting.Playback.MapAndThrowComException(COMException innerException, IPlaybackContext context)
>    at Microsoft.VisualStudio.TestTools.UITesting.Playback.MapAndThrowException(Exception exception, IPlaybackContext context)
>    at Microsoft.VisualStudio.TestTools.UITesting.Playback.MapAndThrowException(Exception exception, String queryId)
>    at Microsoft.VisualStudio.TestTools.UITesting.UITestControl.FindFirstDescendant(String queryId, Int32 maxDepth, Int32& timeLeft)
>    at Microsoft.VisualStudio.TestTools.UITesting.SearchHelper.GetElement(Boolean useCache, ISearchArgument searchArg)
>    at Microsoft.VisualStudio.TestTools.UITesting.SearchHelper.Search(ISearchArgument searchArg)
>    at Microsoft.VisualStudio.TestTools.UITesting.UITestControl.FindInternal()
>    at Microsoft.VisualStudio.TestTools.UITesting.UITestControl.FindControlIfNecessary()
>    at Microsoft.VisualStudio.TestTools.UITesting.UITestControl.SetPropertyPrivate(String propertyName, Object value)
>    at Microsoft.VisualStudio.TestTools.UITesting.UITestControl.<>c__DisplayClass3e.<SetProperty>b__3d()
>    at Microsoft.VisualStudio.TestTools.UITesting.CodedUITestMethodInvoker.InvokeMethod[T](Func`1 function, UITestControl control, Boolean firePlaybackErrorEvent, Boolean logAsAction)
>    at Microsoft.VisualStudio.TestTools.UITesting.UITestControl.SetProperty(String propertyName, Object value)
>    at Microsoft.VisualStudio.TestTools.UITesting.WpfControls.WpfEdit.set_Text(String value)
>    at CUITe.Controls.WpfControls.WpfEdit.set_Text(String value)
>    at CodedUITestProject1.UiMap.MainWindowUiMap.set_FirstNameTextBox(String value) in d:\Roxton\Documents\Visual Studio 2013\Projects\TestWpfApplication\CodedUITestProject1\UiMap\MainWindowUiMap.cs:line 18
>    at CodedUITestProject1.Tests.TestMainWindowGreetings.TestGreetings() in d:\Roxton\Documents\Visual Studio 2013\Projects\TestWpfApplication\CodedUITestProject1\Tests\TestMainWindowGreetings.cs:line 17

Looks like MainWindow can be found but I can't find a single control in it.
Solution files are attached.
[TestWpfApplication.zip](https://github.com/icnocop/cuite/files/134425/TestWpfApplication.zip)

**Comment by FantasticFiasco** [comment]
I'm on it, but won't be able to provide you with a complete working solution faster than tonight.

Short story though, never rely on the `Name` property when searching for elements in a WPF windows, instead mark your elements with the attached property `AutomationProperties.AutomationId` and search for those instead.

**Comment by aannenko** [comment]
Cool! Will give it a try in a couple of minutes.

**Update:**
I get the same exception.

**Comment by FantasticFiasco** [comment]
Here is the complete solution:

``` xaml
<Window
    x:Class="WpfApplication1.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    Title="MainWindow"
    SizeToContent="Height"
    Width="200">

    <StackPanel Margin="8">
        <TextBox
            x:Name="FirstNameTextBox"
            AutomationProperties.AutomationId="ZybHF6Q6IEe-4FJCaqgC6w"
            Width="120"
            Text="First Name"/>

        <TextBox
            x:Name="LastNameTextBox"
            AutomationProperties.AutomationId="rq1eU-P1ekCgWl958B9mMw"
            Margin="0,8"
            Text="Last Name"
            Width="120"/>

        <Button
            AutomationProperties.AutomationId="VfagV9ClEk2oQlaBCDrvIQ"
            Content="Say Hey!"
            VerticalAlignment="Top"
            Width="75"
            Margin="0,0,0,8"
            Click="Button_Click"/>

        <TextBlock
            x:Name="GreetingsTextBlock"
            AutomationProperties.AutomationId="5-1IoR3tekinspUsj8I_LQ"
            TextAlignment="Center"
            Text="You'll see your greeting here"/>
    </StackPanel>
</Window>
```

``` c#
public class MainScreen : Screen
{
    public string FirstNameTextBox
    {
        get { return Find<WpfEdit>(By.AutomationId("ZybHF6Q6IEe-4FJCaqgC6w")).Text; }
        set { Find<WpfEdit>(By.AutomationId("ZybHF6Q6IEe-4FJCaqgC6w")).Text = value; }
    }

    public string LastNameTextBox
    {
        get { return Find<WpfEdit>(By.AutomationId("rq1eU-P1ekCgWl958B9mMw")).Text; }
        set { Find<WpfEdit>(By.AutomationId("rq1eU-P1ekCgWl958B9mMw")).Text = value; }
    }

    public void ClickSayHeyButton()
    {
        Find<WpfButton>(By.AutomationId("VfagV9ClEk2oQlaBCDrvIQ")).Click();
    }

    public string GreetingsTextBlock
    {
        get { return Find<WpfText>(By.AutomationId("5-1IoR3tekinspUsj8I_LQ")).DisplayText; }
    }
}
```

``` c#
[CodedUITest]
public class CodedUITest1
{
    [TestMethod]
    public void TestGreetings()
    {
        // Arrange
        MainScreen mainScreen = Screen.Launch<MainScreen>(@"E:\My Desktop\WpfApplication1\WpfApplication1\bin\Debug\WpfApplication1.exe");
        mainScreen.FirstNameTextBox = "John";
        mainScreen.LastNameTextBox = "Doe";

        // Act
        mainScreen.ClickSayHeyButton();

        // Assert
        Assert.AreEqual("Hi John Doe", mainScreen.GreetingsTextBlock);
    }
}
```

**Comment by FantasticFiasco** [comment]
The automation ids are generated to something that is called a [shortguid](http://madskristensen.net/post/A-shorter-and-URL-friendly-GUID). I generated them using this [tool](https://github.com/FantasticFiasco/guid-generator).

I do believe that the automation id never should be human readable texts due to the fact that these texts often gets changed when e.g. the content of the button gets changed. Keeping the automation id in a state that in no way can be related to what the UI is displaying increases the changes for the id to stay unchanged. That way UI tests won't fail due to changed automation ids.

**Comment by aannenko** [comment]
Cool! Works perfectly, thank you! Could you please update the README.md with something like the code in this solution?

**Comment by FantasticFiasco** [comment]
There is an issue specifying that we need to update the documentation when releasing the official 2.0 version. I've had to focus elsewhere the last months but will probably get some time in the near future.

**Comment by aannenko** [comment]
Sounds awesome! Thank you a lot for your help!

**Comment by FantasticFiasco** [comment]
@aannenko Is it OK if we close this issue?

**Comment by aannenko** [comment]
Yea, definitely! Thanks again!
