### ISSUE TITLE
AppVeyor badge

### ISSUE THREAD

**Issue by FantasticFiasco** [icnocop/cuite#66]
I think we should add a AppVeyor badge to _README.md_, indicating to readers that the project is exorcised by a CI server. As an example, see the badge on [Entity Framework on GitHub](https://github.com/aspnet/EntityFramework/blob/dev/README.md).

The Markdown format of the badge can be found under AppVeyor project settings, but I don't have access to it.

**Comment by FantasticFiasco** [comment]
One aspect I didn't think of is this: If a build only suceeds when one of us are logged into the AppVeyor VM, then we will probably have more builds failing than succeeding, and highlighting that in _README.md_ using a badge probably isn't a good thing?

**Comment by icnocop** [comment]
Right. I would like to add the badge only when we get the build working completely unattended again.

**Comment by icnocop** [comment]
I recently migrated the build to Azure Pipelines and it works unattended. :)
