### ISSUE TITLE
Standalone WpfControl

### ISSUE THREAD

**Issue by aannenko** [icnocop/cuite#67]
Would be very useful to have a standalone (non-abstract) WpfControl class in situations when you need to wait for the control to appear or disappear and it doesn't really matter what type of the control should be there.

**Comment by aannenko** [comment]
Oh sorry! There is WpfCustom...

**Comment by aannenko** [comment]
No, looks like WpfCustom doesn't fit... We already have the WpfControl class so I see two ways: the first one is to leave everything as it is so that everyone who uses the CUITe framework would need to implement some sort of their own "WpfGeneral" control, or to add another WpfControl in the CUITe.Controls.WpfControls namespace and rename the existing one to WpfControlOfT.
@icnocop, @FantasticFiasco, what do you guys think?

**Comment by FantasticFiasco** [comment]
Could you provide a working sample where this new control would be beneficial?

**Comment by aannenko** [comment]
Well... I won't post all my code here because there is a lot of it that is involved in the process but here is a class from which I inherit most of my "page" classes from the page-object pattern.

``` C#
    public abstract class BaseInnerWindow : ScreenObject<WpfGeneralControl>
    {
        protected BaseInnerWindow(By searchConfiguration)
            : base(searchConfiguration)
        {
        }

        protected T NavigateTo<T>(By searchBy, int timeoutMilliseconds = 30000) where T : BaseInnerWindow, new()
        {
            var window = GetScreenObject<T>();
            window.WaitForControlReady(searchBy, timeoutMilliseconds);
            return window;
        }

        private void WaitForControlReady(By searchBy, int timeoutMilliseconds)
        {
            var sWatch = Stopwatch.StartNew();
            var control = Find<WpfGeneralControl>(searchBy);
            if (!control.WaitForControlExist(timeoutMilliseconds))
            {
                throw new UITestControlNotFoundException();
            }

            if (!control.WaitForControlEnabled(timeoutMilliseconds - (int)sWatch.ElapsedMilliseconds))
            {
                throw new UITestControlNotAvailableException();
            }
        }
    }
```

Imagine a wizard and each if its steps is treated as a separate WPF window in my code. I perform navigation to each of these windows using the NavigateTo method. Sometimes there are 5-10 seconds delays between wizard's steps and I have to wait for some of its controls to become accessible.

One more "pro": CUIT has such type of control and it is public. Why should CUITe be different?

**Comment by FantasticFiasco** [comment]
Would #69 fix your problem?

**Comment by aannenko** [comment]
Yea, definitely! Huge thanks!
