### ISSUE TITLE
Add support for the "ControlId" search property/configuration

### ISSUE THREAD

**Issue by icnocop** [icnocop/cuite#74]
Add support for the "ControlId" search property/configuration.

In CUITe v1.0.6, I could specify "ControlId=12345" as a search property, but in v2.0.265 I get the following compilation error:

> CS0117 'By' does not contain a definition for 'ControlId'

**Comment by icnocop** [comment]
As a work-around, I can use `By.SearchProperties("ControlId=12345")`.

**Comment by FantasticFiasco** [comment]
If you wan't I can create a PR for you fixing this.

**Comment by icnocop** [comment]
Thank you

I will work to add support for this as it seems like good practice for me.

Once I create a PR, you can review it, make comments etc., and once you approve, you can merge it. :)

**Comment by icnocop** [comment]
Fixed in v2.0.280-beta
