### ISSUE TITLE
CUITe.Controls.InvalidSearchPropertyNamesException. Class instead of ClassName

### ISSUE THREAD

**Issue by aannenko** [icnocop/cuite#77]
Weirdly enough, I get the InvalidSearchPropertyNamesException whenever I try to find a WPF element using its class name.

``` c#
Find<WpfMenu>(By.ClassName(ContextMenuClassName))
```

It says that the 'Class' property is not supported and then lists the supported properties among which there is a ClassName.

Maybe there is something different between adding search properties to the WpfMenu element (the one I'm currently having problems with) and to the UITestControl (this one is used in the ClassNameConfigurator class)?

Coded UI autogenerated test works fine.

I got CUITe.VS2013 2.0.282-beta

**Comment by icnocop** [comment]
I've run into a similar issue where the control I wanted to find has a custom search property key and so trying to use that custom search property like `By.SearchProperties("Value=0")` would throw the same exception.

I think it's best to just remove validation.

This makes it more flexible anyway.

Thank you.

**Comment by aannenko** [comment]
Thanks Rami.
Is there a chance these changes could get into a new CUITe version today?

**Comment by icnocop** [comment]
Yes, it is building now. :smile:

**Comment by icnocop** [comment]
This is now available on NuGet as CUITe 2.0.294-beta.
