### ISSUE TITLE
Specific version of `CUITe.Silverlight.dll` missing in all of the CUITe.Silverlight NuGet packages

### ISSUE THREAD

**Issue by icnocop** [icnocop/cuite#82]
There are specific versions of `CUITe.Silverlight.dll` missing in all of the CUITe.Silverlight NuGet packages.

For example, `CUITe.Silverlight.dll` may be missing for NuGet packages that target .NET 4.0 and others that target .NET 4.5.

**Comment by icnocop** [comment]
The other thing I'm thinking about is making the appropriate CUITe NuGet package a dependency of the CUITe.Silverlight NuGet package but I'm not sure what the advantages and/or disadvantages are.

**Comment by FantasticFiasco** [comment]
I haven't looked at the NuGet packaging story since we had everything in one package, so I don't understand the context or the problem. If it is something you wan't feedback with I'll start digging around, please let me know.

**Comment by icnocop** [comment]
I'll be looking into fixing the issues with the Silverlight NuGet package. As for the NuGet package dependencies, I think I'll leave that for a subsequent pull request. :) Thank you.

**Comment by icnocop** [comment]
It seems that Visual Studio 2012+ Coded UI Tests are only supported when .NET 4.5 is installed.
[Coded UI test fails to execute in Test Agent 2012 standalone environment (mstest.exe) on .NET 4.0 (e.g. WinXP)](https://connect.microsoft.com/VisualStudio/feedbackdetail/view/788809/coded-ui-test-fails-to-execute-in-test-agent-2012-standalone-environment-mstest-exe-on-net-4-0-e-g-winxp)
[Test Agent 2012 replaces .NET 4.0 with .NET 4.5](https://connect.microsoft.com/VisualStudio/feedback/details/788833/test-agent-2012-replaces-net-4-0-with-net-4-5)
