### ISSUE TITLE
AppVeyor and the desktop

### ISSUE THREAD

**Issue by FantasticFiasco** [icnocop/cuite#85]
I saw that AppVeyor had a git repository, and within that repo i found https://github.com/appveyor/ci/blob/master/scripts/enable-desktop.ps1. Is this something we already use, or could use to fix the problem of having to remote desktop into the AppVeyor mashine?

**Comment by icnocop** [comment]
I've tried to use that before, but the issue still persists.

See the discussion here:
http://help.appveyor.com/discussions/problems/3586-black-screenshots

**Comment by FantasticFiasco** [comment]
Interesting. Sad to see that it didn't work.
