### ISSUE TITLE
Document how to configure ReSharper to use CUITe.sln.DotSettings correctly

### ISSUE THREAD

**Issue by icnocop** [icnocop/cuite#88]
Document how to configure ReSharper to use CUITe.sln.DotSettings correctly.

Which version of ReSharper is required?

In Visual Studio 2013, I go to Resharper > Manage Options... > Solution 'CUITe' team-shared > Add Layer > Open Settings File... > Open "CUITe.sln.DotSettings" > Close.
But then if I try to find code issues in a file which has a using statement within the namespace, Resharper doesn't find any issues.
Do you have any other options in Resharper's Setting Layers for the solution?

**Comment by icnocop** [comment]
This is a continuation of the discussion started here: https://github.com/icnocop/cuite/pull/75#discussion_r59080426

**Comment by FantasticFiasco** [comment]
Would you like this information in _CONTRIBUTING.md_ or somewhere else?

**Comment by icnocop** [comment]
CONTRIBUTING.md would be good. Thank you!
