### ISSUE TITLE
Unexpected control being found when calling `Find<WinButton>(By.ControlName("..."))`

### ISSUE THREAD

**Issue by icnocop** [icnocop/cuite#89]
An unexpected control is being found when calling `Find<WinButton>(By.ControlName("..."))`.

The behavior can be noticed in an existing unit/integration test.

File: .\src\SystemsUnderTest\Sut.WinForms.ScreenObjectsTest\ScreenObjectsTest.cs

```
        [TestMethod]
        public void NavigateToModalDialog()
        {
            // Act
            var dialogScreen = mainScreen.MiddleScreenObject.NavigateToModalDialogScreen();

            // Assert
            Assert.IsTrue(dialogScreen.CloseButtonExists);
        }
```

If I manually run this test, I notice that the Minimize button in the title bar gets clicked instead of the button with the control name `buttonOpenModalDialog`.

Any ideas?

**Comment by FantasticFiasco** [comment]
No idea, but I have noticed strange behaviors when it comes to finding WinForms controls. I'll take a look at the issue.
