### ISSUE TITLE
HtmlControl.GetChildren() returns objects with insufficent search properties?

### ISSUE THREAD

**Issue by matsovef** [icnocop/cuite#92]
I haven't used CUIT or CUITe much so I might have misunderstood this. But lately I run into this problem (simplified example).

In the web page there is a part that has something that looks like follows:

```
<div>
  <p>1</p>
  <p>2</p>
  <p>3</p>
  <p>4</p>
  <p>5</p>
  <p>6</p>
</div>
```

Variable _item_ is set by locating the DIV by using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls.HtmlDiv.
 Then I use it to locate all its children.

```
HtmDiv panel = new HtmlDiv((UITesting.HtmlControls.HtmlDiv)item);
IEnumerable<CUITe.Controls.ControlBase> controls = panel.GetChildren();
foreach (var ctrl in controls)
 {
    if (ctrl is HtmlParagraph)
    {
      HtmlParagraph p = (HtmlParagraph)ctrl;
      TestContext.WriteLine("p = {0}", p.InnerText);
   }
 }
```

The result is

```
p = 1
p = 1
p = 1
p = 1
p = 1
p = 1
```

I made a copy of the GetChildren and WrapUtil methods in HtmlControls in my own code and debugged WrapUtil. I noticed that WrapUtil in turn gets the six paragraphs as expected. But the returned HtmlParagraph objects all look the same. As I understand UITesting doesn't locate a control until you try to fetch something from it. So when p.InnerText evaluates it always finds and returns the first P-element since the only search property is TagName = "P".

I made a try to modify WrapUtil as this to see if I could get a more precise search specification

```
   private static CUITe.Controls.ControlBase WrapUtil(CUITControls.HtmlControl sourceControl)
    {
        CUITe.Controls.ControlBase control;

        string searchProperty = String.Format("TagInstance={0}", sourceControl.TagInstance);
        ...
        switch (sourceControl.TagName.ToLower())
                        {
                            case "p":
                                control = new HtmlParagraph((CUITControls.HtmlCustom)sourceControl, By.SearchProperties(searchProperty));
                                break;
```

Well it worked for the first two returned children. Then it failed for the third child with

```
Microsoft.VisualStudio.TestTools.UITest.Extension.UITestControlNotFoundException: 
The playback failed to find the control with the given search properties. 
Additional Details: 
TechnologyName:  'Web'
TagInstance:  '7'
TagName:  'p'
MaxDepth:  '1'
Instance:  '2'
```

Is this anyway around this or must I solve it myself by switching to only use Microsoft's UITesting?

I used Coded UI Test Builder to see how it would specify the search properties:

```
  this.mUIItemCustom1 = new HtmlCustom(this);
  this.mUIItemCustom1.SearchProperties["TagName"] = "P";
  this.mUIItemCustom1.SearchProperties["Id"] = null;
  this.mUIItemCustom1.SearchProperties[UITestControl.PropertyNames.Name] = null;
  this.mUIItemCustom1.FilterProperties["Class"] = null;
  this.mUIItemCustom1.FilterProperties["ControlDefinition"] = null;
  this.mUIItemCustom1.FilterProperties["TagInstance"] = "6";
```

So I started to think if a

```
HtmlControl.GetChildren(string filterProperties)
```

where you specify which properties of the sourceControl to use as filterProperties on the new control. For instance like this

```
HtmDiv panel = new HtmlDiv((UITesting.HtmlControls.HtmlDiv)item);
IEnumerable<CUITe.Controls.ControlBase> controls = panel.GetChildren("TagInstance");
foreach (var ctrl in controls)
 {
    if (ctrl is HtmlParagraph)
    {
      HtmlParagraph p = (HtmlParagraph)ctrl;
      TestContext.WriteLine("p = {0}", p.InnerText);
   }
 }
```

Not sure whether it solves the problem or not but would give one the possibility to also filter amongst matching controls.

**Comment by FantasticFiasco** [comment]
Hi @matsovef and thank you for reporting the issue.

I will start investigate, and thanks for the extremely detailed report. It seems you've spent a considerable amount of time trying to solve this bug. Your analysis will surely help me to understand the problem at hand.

**Comment by icnocop** [comment]
Fixed in commit https://github.com/icnocop/cuite/commit/97362e78d957f6b72187e092e3f8440f10e88872
Available in NuGet packages with version 2.0.303-beta.

**Comment by matsovef** [comment]
I've tried the fix and works fine for me.

Thanks for a quick response.

**Comment by FantasticFiasco** [comment]
Thanks for reporting it. Please let us know if you experience any other problems.

Thank you!
